// <auto-generated />
using CensusFieldSurvey.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CensusFieldSurvey.DataBase.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250403013358_CriandoProjeto")]
    partial class CriandoProjeto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CensusFieldSurvey.Model.EntitesBD.Research", b =>
                {
                    b.Property<int>("IdResearch")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idResearch");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdResearch"));

                    b.Property<string>("Form")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("form");

                    b.HasKey("IdResearch");

                    b.ToTable("tbResearch");
                });
#pragma warning restore 612, 618
        }
    }
}
